// <auto-generated />
using System;
using FunBoardGames.Database;
using FunBoardGames.Network.SignalR.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FunBoardGames.Database.Migrations
{
    [DbContext(typeof(FunBoardGamesDbContext))]
    [Migration("20260915213238_SET_Game_Attribute")]
    partial class SET_Game_Attribute
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "game_type", new[] { "set", "cant_stop" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FunBoardGames.Database.Entities.BoardGameData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("Deleted_At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<BoardGameType>("GameType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("game_type")
                        .HasDefaultValue(BoardGameType.SET)
                        .HasColumnName("game_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("game")
                        .HasColumnName("name");

                    b.Property<long>("PlayerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(2L)
                        .HasColumnName("player_count");

                    b.HasKey("Id");

                    b.ToTable("Board_Games", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FunBoardGames.Database.Entities.UserCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_token_hash");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("User_Credentials", (string)null);
                });

            modelBuilder.Entity("FunBoardGames.Database.Entities.CantStopGameData", b =>
                {
                    b.HasBaseType("FunBoardGames.Database.Entities.BoardGameData");

                    b.Property<string>("BoardData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("board_data");

                    b.ToTable("CantStop_Games", (string)null);
                });

            modelBuilder.Entity("FunBoardGames.Database.Entities.SETGameData", b =>
                {
                    b.HasBaseType("FunBoardGames.Database.Entities.BoardGameData");

                    b.Property<int?>("ColorAttribute")
                        .HasColumnType("integer")
                        .HasColumnName("color_attribute");

                    b.Property<int?>("CountAttribute")
                        .HasColumnType("integer")
                        .HasColumnName("count_attribute");

                    b.Property<int?>("ShadingAttribute")
                        .HasColumnType("integer")
                        .HasColumnName("shading_attribute");

                    b.Property<int?>("ShapeAttribute")
                        .HasColumnType("integer")
                        .HasColumnName("shape_attribute");

                    b.Property<int>("VisibleCardCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12)
                        .HasColumnName("visible_card_count");

                    b.ToTable("SET_Games", null, t =>
                        {
                            t.HasCheckConstraint("CK_SET_Games_color_attribute", "color_attribute BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_SET_Games_count_attribute", "count_attribute BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_SET_Games_shading_attribute", "shading_attribute BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_SET_Games_shape_attribute", "shape_attribute BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("FunBoardGames.Database.Entities.CantStopGameData", b =>
                {
                    b.HasOne("FunBoardGames.Database.Entities.BoardGameData", null)
                        .WithOne()
                        .HasForeignKey("FunBoardGames.Database.Entities.CantStopGameData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FunBoardGames.Database.Entities.SETGameData", b =>
                {
                    b.HasOne("FunBoardGames.Database.Entities.BoardGameData", null)
                        .WithOne()
                        .HasForeignKey("FunBoardGames.Database.Entities.SETGameData", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
