// <auto-generated />
using System;
using FunBoardGames.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FunBoardGames.Database.Migrations
{
    [DbContext(typeof(FunBoardGamesDbContext))]
    [Migration("20260911165239_AddBoardGamesTpt")]
    partial class AddBoardGamesTpt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FunBoardGames.Database.Entities.BoardGameEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Deleted_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PlayerCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FunBoardGames.Database.Entities.UserCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserCredentials", (string)null);
                });

            modelBuilder.Entity("FunBoardGames.Database.Entities.CantStopGameEntity", b =>
                {
                    b.HasBaseType("FunBoardGames.Database.Entities.BoardGameEntity");

                    b.Property<string>("BoardData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.ToTable("CantStopGames", (string)null);
                });

            modelBuilder.Entity("FunBoardGames.Database.Entities.SETGameEntity", b =>
                {
                    b.HasBaseType("FunBoardGames.Database.Entities.BoardGameEntity");

                    b.Property<float>("GuessTime")
                        .HasColumnType("real");

                    b.ToTable("SETGames", (string)null);
                });

            modelBuilder.Entity("FunBoardGames.Database.Entities.CantStopGameEntity", b =>
                {
                    b.HasOne("FunBoardGames.Database.Entities.BoardGameEntity", null)
                        .WithOne()
                        .HasForeignKey("FunBoardGames.Database.Entities.CantStopGameEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FunBoardGames.Database.Entities.SETGameEntity", b =>
                {
                    b.HasOne("FunBoardGames.Database.Entities.BoardGameEntity", null)
                        .WithOne()
                        .HasForeignKey("FunBoardGames.Database.Entities.SETGameEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
